### PR TITLE
Break down osmosis-installer.py and break down the code 

### PR DESCRIPTION
**Pull request by stackman27**
Closes: #20 
Part of: #50 

This PR 
1. separate the code in different smaller files that would be easier to maintain
2. create a simple script that would merge all scripts in a single one
3. still serve the single file in https://get.osmosis.zone/install

### CODE REVIEW

**Comment by ValarDragon** [comment]
Exciting for maintainability!

(minor comment) Lets add __pycache to the gitignore and delete from here

**Comment by stackman27** [comment]
> I believe there are too many files in the installer, which can lead to decreased maintainability. While attempting to improve readability, we may have gone too far in the other direction.
> 
> To find a better balance, it's worth considering structuring the installer into `logic modules` rather than having a separate file for every single function. For example, a `prerequisite.py` module could install all the required dependencies, like Go and Rust. I would limit the number of modules to 4-5 for ease of management.
> 
> As a next step, have you considered how to merge the modules back into a single file?


Gotchu currently, i'm the way i've split up the file is based on flows. It works something like this; 
1. Everything flow leads upto initSetup 
2. I broke functions down into their specific files if they require additional installations during initSetup for ex installing rust 

Screen Shot 2023-02-14 at 11 42 23 AM

**Comment by stackman27** [comment]
@niccoloraspa @ValarDragon added a bash script that merges all the files. (combine.sh)

**Comment by stackman27** [comment]
look into https://jinja.palletsprojects.com/en/3.1.x/api/#basics

**Pull request closed without merging**
